# Generated by Django 5.1.4 on 2025-01-10 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_candidate_about_me_image_candidate_resume_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='experience_image',
        ),
        migrations.AddField(
            model_name='candidate',
            name='experience_image',
            field=models.ImageField(default=1, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
